"""Export persisted research conversations as Markdown and polished PDF files."""

from __future__ import annotations

import re
from datetime import UTC, datetime
from html import escape
from io import BytesIO
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    KeepTogether,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from src.citation import safe_external_url

FONT_NAME = "NotoSansSC"
FONT_PATH = Path(__file__).resolve().parents[1] / "assets" / "fonts" / "NotoSansSC-Variable.ttf"
pdfmetrics.registerFont(TTFont(FONT_NAME, str(FONT_PATH)))


def _exported_at() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")


def export_filename(conversation: dict[str, Any], extension: str) -> str:
    """Return a short filesystem-safe export name."""
    title = str(conversation.get("title") or "research").strip()
    slug = re.sub(r"[^\w\u4e00-\u9fff-]+", "-", title, flags=re.UNICODE).strip("-_")
    return f"{(slug or 'research')[:64]}.{extension.lstrip('.')}"


def _citation_markdown(citation: dict[str, Any], index: int) -> str:
    display = str(citation.get("display_source") or citation.get("source") or "Source")
    url = safe_external_url(str(citation.get("url") or ""))
    label = f"[{display}]({url})" if url else display
    metadata = [
        str(value) for value in (citation.get("publisher"), citation.get("published_at")) if value
    ]
    if citation.get("trust_tier") and citation.get("source_type") in {"web", "financial"}:
        metadata.append(f"Tier {citation['trust_tier']}")
    suffix = f" - {' | '.join(metadata)}" if metadata else ""
    lines = [f"{index}. **{citation.get('icon', 'SOURCE')}** {label}{suffix}"]
    if citation.get("snippet"):
        quote = str(citation["snippet"]).replace("\n", " ").strip()
        lines.append(f"   > {quote}")
    return "\n".join(lines)


def build_markdown_export(
    conversation: dict[str, Any], messages: list[dict[str, Any]], lang: str = "zh"
) -> str:
    """Create a portable UTF-8 Markdown research record with full provenance."""
    title = conversation.get("title") or ("未命名研究" if lang == "zh" else "Untitled research")
    exported_label = "导出时间" if lang == "zh" else "Exported"
    source_heading = "来源" if lang == "zh" else "Sources"
    role_labels = {
        "user": "用户" if lang == "zh" else "User",
        "assistant": "分析" if lang == "zh" else "Analysis",
        "system": "系统" if lang == "zh" else "System",
    }
    parts = [f"# {title}", "", f"> {exported_label}: {_exported_at()}", ""]
    for message in messages:
        parts.extend(
            [f"## {role_labels.get(message['role'], message['role'])}", "", message["content"], ""]
        )
        citations = message.get("citations") or []
        if citations:
            parts.extend([f"### {source_heading}", ""])
            for index, citation in enumerate(citations, 1):
                parts.extend([_citation_markdown(citation, index), ""])
    parts.extend(["---", "", "Generated by SiliconDreams"])
    return "\n".join(parts).strip() + "\n"


def _inline_markup(text: str) -> str:
    """Convert a small safe subset of Markdown to ReportLab paragraph markup."""
    escaped = escape(text, quote=False)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<font name='Courier'>\1</font>", escaped)
    escaped = re.sub(r"\[(\d+)\]", r"<font color='#1557a0'><super>[\1]</super></font>", escaped)
    return escaped


def _table_cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def _is_table_separator(line: str) -> bool:
    cells = _table_cells(line)
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell.replace(" ", "")) for cell in cells)


def _markdown_flowables(text: str, styles: dict[str, ParagraphStyle], width: float) -> list[Any]:
    lines = text.splitlines()
    flowables: list[Any] = []
    paragraph_buffer: list[str] = []

    def flush_paragraph() -> None:
        if paragraph_buffer:
            joined = " ".join(part.strip() for part in paragraph_buffer)
            flowables.append(Paragraph(_inline_markup(joined), styles["body"]))
            flowables.append(Spacer(1, 2.5 * mm))
            paragraph_buffer.clear()

    index = 0
    while index < len(lines):
        line = lines[index].rstrip()
        if not line.strip():
            flush_paragraph()
            index += 1
            continue

        if (
            "|" in line
            and index + 1 < len(lines)
            and "|" in lines[index + 1]
            and _is_table_separator(lines[index + 1])
        ):
            flush_paragraph()
            rows = [_table_cells(line)]
            index += 2
            while index < len(lines) and "|" in lines[index] and lines[index].strip():
                rows.append(_table_cells(lines[index]))
                index += 1
            column_count = max(len(row) for row in rows)
            normalized = [row + [""] * (column_count - len(row)) for row in rows]
            cell_style = styles["table"]
            data = [
                [Paragraph(_inline_markup(cell), cell_style) for cell in row] for row in normalized
            ]
            table = Table(data, colWidths=[width / column_count] * column_count, repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16324f")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#b7c2cc")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 4),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        (
                            "ROWBACKGROUNDS",
                            (0, 1),
                            (-1, -1),
                            [colors.white, colors.HexColor("#f3f6f8")],
                        ),
                    ]
                )
            )
            flowables.extend([table, Spacer(1, 3 * mm)])
            continue

        heading = re.match(r"^(#{1,4})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            level = min(len(heading.group(1)), 3)
            flowables.extend(
                [
                    Paragraph(_inline_markup(heading.group(2)), styles[f"heading{level}"]),
                    Spacer(1, 1.5 * mm),
                ]
            )
            index += 1
            continue

        bullet = re.match(r"^\s*[-*]\s+(.+)$", line)
        numbered = re.match(r"^\s*(\d+)[.)]\s+(.+)$", line)
        if bullet or numbered:
            flush_paragraph()
            content = bullet.group(1) if bullet else numbered.group(2)
            marker = "-" if bullet else f"{numbered.group(1)}."
            flowables.append(
                Paragraph(_inline_markup(content), styles["bullet"], bulletText=marker)
            )
            index += 1
            continue

        if line.startswith("> "):
            flush_paragraph()
            flowables.extend(
                [Paragraph(_inline_markup(line[2:]), styles["quote"]), Spacer(1, 2 * mm)]
            )
            index += 1
            continue

        paragraph_buffer.append(line)
        index += 1

    flush_paragraph()
    return flowables


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "SDTitle",
            parent=base["Title"],
            fontName=FONT_NAME,
            fontSize=22,
            leading=29,
            textColor=colors.HexColor("#10263a"),
            alignment=TA_CENTER,
            spaceAfter=5 * mm,
        ),
        "meta": ParagraphStyle(
            "SDMeta",
            fontName=FONT_NAME,
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#667788"),
            alignment=TA_CENTER,
        ),
        "role": ParagraphStyle(
            "SDRole",
            fontName=FONT_NAME,
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#a36500"),
            spaceBefore=4 * mm,
            spaceAfter=2 * mm,
        ),
        "body": ParagraphStyle(
            "SDBody",
            fontName=FONT_NAME,
            fontSize=9.3,
            leading=15,
            textColor=colors.HexColor("#202830"),
        ),
        "heading1": ParagraphStyle(
            "SDH1",
            fontName=FONT_NAME,
            fontSize=14,
            leading=19,
            textColor=colors.HexColor("#16324f"),
        ),
        "heading2": ParagraphStyle(
            "SDH2",
            fontName=FONT_NAME,
            fontSize=12,
            leading=17,
            textColor=colors.HexColor("#16324f"),
        ),
        "heading3": ParagraphStyle(
            "SDH3",
            fontName=FONT_NAME,
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor("#294f70"),
        ),
        "bullet": ParagraphStyle(
            "SDBullet",
            fontName=FONT_NAME,
            fontSize=9.2,
            leading=14,
            leftIndent=6 * mm,
            firstLineIndent=-4 * mm,
            spaceAfter=1 * mm,
        ),
        "quote": ParagraphStyle(
            "SDQuote",
            fontName=FONT_NAME,
            fontSize=8.5,
            leading=13,
            leftIndent=5 * mm,
            borderColor=colors.HexColor("#d2a34b"),
            borderWidth=0,
            borderPadding=3,
            textColor=colors.HexColor("#56616b"),
            backColor=colors.HexColor("#f7f4ed"),
        ),
        "table": ParagraphStyle(
            "SDTable",
            fontName=FONT_NAME,
            fontSize=6.7,
            leading=9,
            textColor=colors.HexColor("#202830"),
        ),
        "source": ParagraphStyle(
            "SDSource",
            fontName=FONT_NAME,
            fontSize=7.6,
            leading=11,
            leftIndent=4 * mm,
            firstLineIndent=-4 * mm,
            textColor=colors.HexColor("#3f4b55"),
            spaceAfter=1.5 * mm,
        ),
    }


def build_pdf_export(
    conversation: dict[str, Any], messages: list[dict[str, Any]], lang: str = "zh"
) -> bytes:
    """Create an A4 PDF with CJK-safe text, tables, citations and page numbers."""
    buffer = BytesIO()
    page_width, page_height = A4
    margin = 18 * mm
    content_width = page_width - 2 * margin
    styles = _styles()
    title = conversation.get("title") or ("未命名研究" if lang == "zh" else "Untitled research")

    def page_decoration(canvas, document) -> None:
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#d8dde2"))
        canvas.line(margin, page_height - 12 * mm, page_width - margin, page_height - 12 * mm)
        canvas.setFont(FONT_NAME, 7)
        canvas.setFillColor(colors.HexColor("#667788"))
        canvas.drawString(margin, 9 * mm, "SILICON DREAMS")
        canvas.drawRightString(page_width - margin, 9 * mm, str(document.page))
        canvas.restoreState()

    document = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=20 * mm,
        bottomMargin=16 * mm,
        title=title,
        author="SiliconDreams",
    )
    frame = Frame(
        document.leftMargin,
        document.bottomMargin,
        document.width,
        document.height,
        id="normal",
    )
    document.addPageTemplates(PageTemplate(id="report", frames=[frame], onPage=page_decoration))

    exported_label = "导出时间" if lang == "zh" else "Exported"
    source_heading = "引用溯源" if lang == "zh" else "Sources"
    role_labels = {
        "user": "用户问题" if lang == "zh" else "User",
        "assistant": "分析回答" if lang == "zh" else "Analysis",
        "system": "系统" if lang == "zh" else "System",
    }
    story: list[Any] = [
        Paragraph(escape(title), styles["title"]),
        Paragraph(f"{exported_label}: {_exported_at()}", styles["meta"]),
        Spacer(1, 7 * mm),
    ]
    for message in messages:
        role = role_labels.get(message["role"], message["role"])
        story.append(Paragraph(escape(role), styles["role"]))
        story.extend(_markdown_flowables(message["content"], styles, content_width))
        citations = message.get("citations") or []
        if citations:
            citation_flowables: list[Any] = [Paragraph(source_heading, styles["heading3"])]
            for index, citation in enumerate(citations, 1):
                display = escape(
                    str(citation.get("display_source") or citation.get("source") or "Source")
                )
                url = safe_external_url(str(citation.get("url") or ""))
                if url:
                    display = (
                        f'<link href="{escape(url, quote=True)}" color="#1557a0">{display}</link>'
                    )
                metadata = [
                    escape(str(value))
                    for value in (citation.get("publisher"), citation.get("published_at"))
                    if value
                ]
                suffix = f" - {' | '.join(metadata)}" if metadata else ""
                citation_flowables.append(
                    Paragraph(
                        f"[{index}] {escape(str(citation.get('icon', 'SOURCE')))} {display}{suffix}",
                        styles["source"],
                    )
                )
                if citation.get("snippet"):
                    citation_flowables.append(
                        Paragraph(escape(str(citation["snippet"])), styles["quote"])
                    )
            story.append(KeepTogether(citation_flowables[:2]))
            story.extend(citation_flowables[2:])
            story.append(Spacer(1, 3 * mm))
    story.append(Paragraph("Generated by SiliconDreams", styles["meta"]))
    document.build(story)
    return buffer.getvalue()
